
default: &default
  adapter: postgresql
  encoding: unicode

  pool: 5

development:
  <<: *default
  database: amazonia_development

test:
  <<: *default
  database: amazonia_test

production:
  <<: *default
  database: amazonia_production
  username: amazonia
  password: <%= ENV['AMAZONIA_DATABASE_PASSWORD'] %>
